### ISSUE TITLE
Provide more information when manifest.json fails validation

### ISSUE THREAD

**Issue by carlin-q-scott** [webextension-toolbox/webextension-toolbox#106]
## Expected Behavior

manifest.json passes validation.

## Current Behavior
I get this error with no other context:
> You need to provide a valid 'manifest.json'

## Steps to Reproduce (for bugs)

1. `npm install --save-dev webextension-toolbox`
2. `npx webextension-toolbox build firefox`

## Context

I'm trying to build https://github.com/carlin-q-scott/browser-media-players/tree/webextension-toolbox but my manifest.json is failing validation.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |     2.0.0    |
| node                    |     v8.12.0    |
| OS                      |    Windows 10     |
| browser                 |    Firefox     |
| terminal environment |    Powershell v5.1.17134.228    |

**Comment by balcsida** [comment]
Hi @carlin-q-scott,

Thank you for bringing up this improvement idea.
I agree with you, the error message for this could be improved.

I also checked your repo and the cause in your case that there is no seperate folder which contains all of your source for the extension itself (the 'src' by default). I  kindly ask you to reorganize your code and separate your browser extension's code from the rest of the necessary stuff.
I think the error message for this case (no source folder found, no manifest found in the source folder) should be also improved.

Please let me know if you have any question regarding this matter.

Warm regards,
@balcsida

**Comment by bboydflo** [comment]
I had the same issue today, and found out that webextension-toolbox uses `webpack-webextension-plugin` (https://github.com/webextension-toolbox/webpack-webextension-plugin) under the hood. maybe the issue should be raised in there

**Comment by carlin-q-scott** [comment]
@balcsida Thank you for providing me with a solution to my particular issue but the overall issue is that people don't know why validation fails, or in my case, why I was told validation had failed when in fact the issue wasn't related to the manifest at all. If you're ok with reviewing everyone's source code when they get a validation error then we do in fact have a workaround. I however think that that's an unfair use of your time.

**Comment by balcsida** [comment]
Hi @carlin-q-scott,

While I understand that improving manifest.json validation output is necessary, I think I wasn't clear about the workaround part.
The workaround here is to build up folder structure where WebExtension Toolbox expects it, based on the output of WebExtension Generator. I understand that this requires manual work and I think this would deserve some additional documentation.

I checked the README and while it only states that this tool provides validation only (telling if valid or not), I think this is something that needs to be addressed to make easier to developers adapt WebExtension Toolbox, therefore I raised the severity on this issue to "major".

Cheers,
@balcsida

**Comment by HaNdTriX** [comment]
Here are some hints on how to get started with this issue:

webextension-toolbox needs the `manifest.json` in order to preconfigure the `WebextensionPlugin`.

https://github.com/webextension-toolbox/webextension-toolbox/blob/0183506baaf96eb0ae56cd70da71807bc8dbb65d/src/webpack-config.js#L35

If we want to improve the validation step we might want to do it here:

https://github.com/webextension-toolbox/webextension-toolbox/blob/4a66498303f08a99a0c5e9df7e2587f0fbdc95e7/src/utils/get-extension-info.js#L18-L24

Please note that the Error is only thrown, if there is no valid `JSON` file. A deeper manifest validation is done later via [webpack-webextension-plugin](https://github.com/webextension-toolbox/webpack-webextension-plugin). If you want to improve that validator you can do it here:

Example: https://github.com/webextension-toolbox/webpack-webextension-plugin/blob/master/manifest-utils/validate.js

**Comment by vincentreynaud** [comment]
Hi!

I am building a browser extension, [study-assist](https://github.com/vincentreynaud/study-assist/tree/extension-setup-vincent], and was running into the same issue `You need to provide a valid 'manifest.json'`. I couldn't really understand what was wrong with my folder structure, until I understood that `webextension-toolbox` looks by default into an `app` folder for the source code (mentioned in the build [syntax documentation](https://github.com/webextension-toolbox/webextension-toolbox#syntax-1)). So to solve this I just had to specify my source folder: `webextension-toolbox build --src 'build'`. As you mention @balcsida, maybe this would deserve additional documentation, and more specific error handling for cases which fall out of the expected folder structure would be helpful.

**Comment by vincentreynaud** [comment]
Something else that is unclear to me - this might belong in another discussion - is how to wire `webextension-toolbox` with my react app so that I have a single build script to run. At the moment I am running `react-scripts build && webextension-toolbox build --src 'build'`, so a first react build script, and then the webextension-toolbox build - taking my compiled `build` folder as source. It's all right, but the documentation mentions that `webextension-toolbox` works with react.js out of the box. Is it possible to better implement that?

Cheers!

**Comment by balcsida** [comment]
Hi @vincentreynaud,

Thank you for the feedback!

I'm already working on PR #115 which will address some of the issues you mention, but adding an extra check to make source the --src folder is set looks an easy task.

Kind regards,
@balcsida
