### ISSUE TITLE
QUESTION :: How to Run Development Locally

### ISSUE THREAD

**Issue by james-r-smith** [webextension-toolbox/webextension-toolbox#120]
## Context

I'm new to front-end / web extension development. I would like to develop my WebExtension locally. I'm unsure how local development is done with this package. `build` is working fine with `Load Temporary Add-on...` in FireFox, but is constantly refreshing the add-on the development process for extension developers? I was hoping there would be a live-reload, and I could just open my browser to see live changes. I'm not sure what the use of `dev` is for.

I tried to connect to `localhost:35729` within my browser, but I'm only getting the message: `Upgrade Required`. I believe this websocket is only for listening to code changes. 😅

Any insight on the development process using this tool would be much appreciated. Thanks!

**Comment by balcsida** [comment]
Hi @james-r-smith,

My apologies for the late reply. Happy new year to you!
I'm not sure what would you like to achieve with your extension. If I suspect correctly, you would like to see HTML page after you load your extension.
While that is certainly possible, WebExtensions are a little bit different from a normal Web application: you can extend the capabilities of your browser and/or the pages you visit. For example, I'm using [Refined GitHub](https://github.com/sindresorhus/refined-github) to enhance my experience on github.com. The other example would be Grammary, which checks my grammar mistakes while I'm typing this text to the text box.

WebExtension Toolbox helps with the development to extensions which are similar to the examples above. If you use the `dev` mode, `Load Temporary Add-on...` in Firefox, and you develop an extension for github.com, you don't need to refresh github.com manually every time you make a change in your extension code, because WebExtension Toolbox will do that for you.
Additionally, if you would like to develop a cross-browser extension - that works in Chrome, Firefox, Opera - you don't really need to worry about that as it includes the necessary library to polyfill the differences between those browsers.

For more information, I would recommend you to check out the [Browser Extensions documentation on MDN](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions). If you have any further question I can help with, please, let me know, and I will try to answer them.

Kind regards,
@balcsida

**Comment by balcsida** [comment]
Hi @james-r-smith,

I was wondering if you have had time to check my previous comment.
If it is not a problem for you, I will go ahead and close this issue now.
Please let me know if you have any further question regarding this matter.

Kind regards,
@balcsida

**Comment by alechemy** [comment]
As someone new to this toolkit, and WebExtension development generally, I think I understand where @jameschensmith is coming from -- I encountered the same issue myself.

The README for this project instructs the user to begin development by running `webextension-toolbox dev <vendor>`, e.g.  `webextension-toolbox dev chrome`. 

It's not entirely clear where to go from here.

Users such as myself will likely go to the terminal output, which includes:
`webpack-webextension-plugin listens on ws://localhost:35729`
and might reasonably conclude that they need to visit either `ws://localhost:35729` or `localhost:35729`, neither of which will work.

If I understand correctly, the 'actual' dev workflow after running `webextension-toolbox dev` is to install the compiled extension into the correct browser. For me, this meant opening Chrome, navigating to `chrome://extensions/`, clicking "Load unpacked", then selecting the `dist/chrome` project directory.

It'd be nice if any of the above info were included in the README.
