### ISSUE TITLE
Files copied in webextension-toolbox-config.js are not included in .zip package

### ISSUE THREAD

**Issue by joelspadin** [webextension-toolbox/webextension-toolbox#136]
## Expected Behavior

If you have a webextension-toolbox-config.js that uses copy-webpack-plugin to copy files into the build directory, those files should get included in the .zip package.

## Current Behavior

The ZipPlugin added at [webpack-config.js line 183](https://github.com/webextension-toolbox/webextension-toolbox/blob/0183506baaf96eb0ae56cd70da71807bc8dbb65d/src/webpack-config.js#L183) runs before any copy-webpack-plugin defined in webextension-toolbox-config.js, and it misses any copied files.

## Steps to Reproduce (for bugs)

Install React:

```
npm i -S react
```

Set up a webpack configuration that defines React as an external library and copies it into the build directory.

```js
// webextension-toolbox-config.js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    webpack: (config, { dev }) => {
        config.externals = {
            "react": "React",
        };

        const mode = dev ? 'development' : 'production.min';
        config.plugins.push(new CopyPlugin([
            {
                from: `../node_modules/react/umd/react.${mode}.js`,
                to: 'scripts/react/react.js',
                cache: true
            },
        ]));
        return config;
    }
};
```

Build the extension:

```
webextension-toolbox build chrome
```

react.js will be copied to /dist/chrome/scripts/react, but it won't be included in packages/*.chrome.zip.

## Context

I have been able to work around this by adding the following to my webextension-toolbox-config.js to move ZipPlugin to the end of the plugins list:

```js
module.exports = {
    webpack: (config, { dev }) => {
        ...
        for (let i = 0; i < config.plugins.length; i++) {
            if (config.plugins[i] instanceof ZipPlugin) {
                let plugins = config.plugins.splice(i, 1);
                config.plugins.push(...plugins);
                break;
            }
        }
        return config;
    }
};
```

I could also only make React an external library in dev builds because I'm mainly doing this to speed up builds, but that would require making changes to how my options page links scripts based on the build mode, so I'd like to avoid that.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 3.0.0        |
| node                    |  11.6.0       |
| OS                      |  Windows 10 build 17763      |

**Comment by HaNdTriX** [comment]
Thanks for raising this issue. webextension-toolbox copies all assets for you.  The problem with your code is that you are copying the assets to the src directory instead of the internal target directory.

```js
// webextension-toolbox-config.js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    webpack: (config, { dev }) => {
        config.plugins.push(new CopyPlugin([
            {
                from: `../node_modules/react/umd/react.${mode}.js`,
                to: config.target, // ⬅️ Here is an example
                cache: true
            },
        ]));
        return config;
    }
};
```

[More Examples](https://github.com/webextension-toolbox/webextension-toolbox/blob/master/src/webpack-config.js#L151-L165)

Nevertheless why are you copying react here at all?

Just use 

```js
import React from 'react'
```

and webextension-toolbox will do the rest for you.

Does this solve your issue? If yes please close it 😊.

**Comment by ChaosinaCan** [comment]
Thanks. I'll check if that works soon.

I reduced my example to just react, but I have a few other react libraries that I'm setting as external as well. I don't remember the exact reason I started doing this, but I believe it was either because I noticed an improvement in build times when not bundling react, or because I was having trouble getting source maps to play nicely with Chrome's debugger.

**Comment by ChaosinaCan** [comment]
Unfortunately, that does not work.

"config.target" doesn't exist, but looking at [webpack-config.js](https://github.com/webextension-toolbox/webextension-toolbox/blob/master/src/webpack-config.js#L73) I'm assuming that "config.output.path" is what you meant.

I tried this:

```js
            {
                from: `../node_modules/react/umd/react.${mode}.js`,
                to: join(config.output.path, 'scripts/react/react.js'),
                cache: true
            },
```

But CopyPlugin appears to treat paths as relative to the output unless told otherwise, so that does the same thing as what I had before.

Either way, the build log indicates that the react scripts are compiled assets, but they still don't get added to the .zip package unless I reorder the plugins so the ZipPlugin is last.

```
√ success webpack compiled in 3s 363ms
Time: 3369ms
Built at: 02/22/2019 12:42:06 AM
                                                   Asset       Size  Chunks                    Chunk Names
..\..\packages\webextension-example.v0.0.0.opera.crx.zip    253 KiB          [emitted]  [big]
...
                              scripts/react/react-dom.js    105 KiB          [emitted]
                            scripts/react/react-modal.js   30.3 KiB          [emitted]
                                  scripts/react/react.js   12.3 KiB          [emitted]
...
```

**Comment by bboydflo** [comment]
@ChaosinaCan and @HaNdTriX I fixed this by doing something like this, it's a bit hacky but it worked for me 👍 

```js
const CopyWebpackPlugin = require('copy-webpack-plugin')
const webpack = require('webpack')

module.exports = {
  webpack: (config, { dev, vendor }) => {

    // copy js files to /dist
    // TODO: do not copy jquery
    config.plugins.unshift(new CopyWebpackPlugin([
      { from: 'copy/**/*' }
    ]))

    return config
  }
}
```

**Comment by HaNdTriX** [comment]
@bboydflo https://github.com/webpack-contrib/copy-webpack-plugin/issues/357 😅

**Comment by ChaosinaCan** [comment]
@bboydflo For some reason I'd overlooked the possibility of inserting the CopyPlugin at the front of the plugins list instead of pushing it onto the end. I think that would work the same as my hack to move the ZipPlugin to the end, and it's a lot simpler.

**Comment by bboydflo** [comment]
@ChaosinaCan yes, it's not intuitive, but hope it solves the problem for now.
