### ISSUE TITLE
Does WebExtention has support for Safari?

### ISSUE THREAD

**Issue by jairorudas** [webextension-toolbox/webextension-toolbox#78]

**Comment by balcsida** [comment]
Hi @jairorudas,

Thanks for raising this question!

No, WebExtension Toolbox does not support Safari and I don't think we will support it in the near future due to the following reasons:

- Safari has very different APIs.
- Safari Extensions are deprecated, Safari 12 is the last release to support them.
- The new way is Safari App Extensions, which is basically a macOS App. You need XCode and other tools to develop and distribute it.

I hope that this answers your question and if you have any additional questions or insights, please let me know! 🙂 

Kind regards,
@balcsida

**Comment by balcsida** [comment]
Based on your last comment, I closed this issue.
Please reopen it anytime if you experience any improvement in Safari APIs or you think I missed something.

**Comment by parasharrajat** [comment]
Hey, I think we can build up for Safari as well. 
[Safari Web Extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions).
